close all;
I = imread('winter girl.jpg');
figure, imshow(I);
I = rgb2gray(I);
subplot(2,2,3),imhist(I);
Z = imread('window dust.jpg');
Z = rgb2gray(Z);
subplot(2,2,2), imhist(Z);
X = imread('the cave.jpg');
X = rgb2gray(X);
figure;
subplot(2,2,1),imhist(Z);
subplot(2,2,2),imshow(Z);
E = histeq(x);
subplot(2,2,3),imhist(E);
subplot(2,2,4),imshow(E);
I = double(I);
I = I/ max(I(:));
figure, imshow(I,[]);
Y = log(1+I);
figure, imshow(Y,[]);
